### ISSUE TITLE
AuxRecipeManager Null Pointer Exception

### ISSUE THREAD

**Issue by NanoCE** [Shadows-of-Fire/FastSuite#31]
Modpack: Life in the Village 3 v.2.4
Mod: Storage Drawers
MC Version: 1.19.2

While I submitted a bug report with Storage Drawers, they 400+ issues open, so I thought this might be better to also report here.
Attempting to place iron within the Storage Drawers "compacting drawer" causes this issue. It specifically crashes the client, as this crashed to desktop while I was on a server. This is repeatable and can be trigger in singleplayer as well. Please let me know if you'd like any further information. The Crashlog can be found below.

[crash-2023-11-07_22.54.18-client.txt](https://github.com/Shadows-of-Fire/FastSuite/files/13293271/crash-2023-11-07_22.54.18-client.txt)

**Comment by Shadows-of-Fire** [comment]
The underlying crash here is coming out of passive skill tree:
```
Caused by: java.lang.NullPointerException: Cannot invoke "daripher.skilltree.api.PlayerContainer.getViewingPlayer()" because "this.f_39323_" is null
	at net.minecraft.world.inventory.CraftingContainer.getViewingPlayer(CraftingContainer.java:1020) ~[client-1.19.2-20220805.130853-srg.jar%23681!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:inventory.AccessorCraftingContainer,pl:mixin:APP:skilltree.mixins.json:minecraft/MixinCraftingContainer,pl:mixin:A}
	at daripher.skilltree.container.ContainerHelper.getViewingPlayer(ContainerHelper.java:22) ~[PassiveSkillTree-1.19.2-BETA-0.5.10b.jar%23599!/:0.5.10b] {re:mixin,re:classloading}
	at daripher.skilltree.recipe.WeaponPoisoningRecipe.matches(WeaponPoisoningRecipe.java:27) ~[PassiveSkillTree-1.19.2-BETA-0.5.10b.jar%23599!/:0.5.10b] {re:classloading}
	at daripher.skilltree.recipe.WeaponPoisoningRecipe.m_5818_(WeaponPoisoningRecipe.java:20) ~[PassiveSkillTree-1.19.2-BETA-0.5.10b.jar%23599!/:0.5.10b] {re:classloading}
	at shadows.fastsuite.AuxRecipeManager.lambda$getRecipesFor$3(AuxRecipeManager.java:64) ~[FastSuite-1.19.2-4.1.1.jar%23514!/:4.1.1] {re:mixin,re:classloading,pl:mixin:APP:polymorph-integrations.forge.mixins.json:fastsuite.PolymorphMixinAuxRecipeManager,pl:mixin:A}
```

It just happens to look like FS because FS is controlling crafting operations, but it seems the root cause is one of PST's recipes not accounting for the potential of being crafted without player context (as is being done by the compacting drawer).

**Comment by NanoCE** [comment]
Thank you @Shadows-of-Fire, that was some of the fastest support I've ever gotten. It's highly respected and appreciated.
